export const CATALOG = [
  {
    id: 1,
    title: "Starter Package",
    description: "Perfect for beginners to start earning daily profits.",
    minInvestment: 50,
    maxInvestment: 500,
    durationDays: 30,
    roiDailyPercent: 1.5,
    image: "https://placehold.co/600x400",
    active: true,
  },
  {
    id: 2,
    title: "Silver Package",
    description: "Best value for intermediate investors.",
    minInvestment: 500,
    maxInvestment: 2000,
    durationDays: 60,
    roiDailyPercent: 2.0,
    image: "https://placehold.co/600x400",
    active: true,
  },
  {
    id: 3,
    title: "Gold Package",
    description: "Premium package for serious investors.",
    minInvestment: 2000,
    maxInvestment: 10000,
    durationDays: 90,
    roiDailyPercent: 2.5,
    image: "https://placehold.co/600x400",
    active: true,
  },
  {
    id: 4,
    title: "Platinum Package",
    description: "Maximize your profits with long-term growth.",
    minInvestment: 10000,
    maxInvestment: 50000,
    durationDays: 180,
    roiDailyPercent: 3.0,
    image: "https://placehold.co/600x400",
    active: true,
  },
];
